---

- include_vars: "/src/{{ item }}"
  with_items: "{{ var_files }}"
  when: var_files is defined and var_files

- include: install.yml

- name: Make Django user
  user:
    name: "{{ django_user }}"
    uid: 1000
    group: root
    state: present
    createhome: yes
    home: "{{ django_root }}"

- name: Create application log directory
  file:
    path: "{{ django_log_dir }}"
    state: directory
    owner: "{{ django_user }}"

- include: virtualenv.yml

- include: statics.yml

- name: Copy base entrypoint scripts
  copy:
    src: "{{ role_path }}/files/{{ item }}" 
    dest: "/usr/bin/{{ item }}"
    owner: root
    group: root
    mode: 0775
  with_items:
    - entrypoint.sh
    - wait_on_postgres.py
    - manage_django.sh

- name: Copy any extra script templates
  template:
    src: "/src/{{ item }}"
    dest: "/usr/bin/{{ item | basename | splitext }}[0]"
    owner: root
    group: root
    mode: 0775
  with_items: "{{ script_templates }}"
  when: script_templates is defined and script_templates