---
- name: Why isn't build command provided
  debug: 
    msg: "this is the bundle build command {{ bundle_build_cmd }} and this is the directory {{ bundle_build_dir }}"

- name: Run specified bundle build command if provided
  shell: "{{ bundle_build_cmd }}"
  args:
    chdir: "{{ bundle_build_dir }}"
  when: bundle_build_cmd is defined and bundle_build_cmd

- name: Remove staticfiles dir
  file: 
    name: "{{ django_static_root }}"
    state: absent

- name: Make staticfiles dir
  file:
    name: "{{ django_static_root }}"
    state: directory
    owner: "{{ django_user }}"
    group: root
    mode: 0775

- name: Collect staticfiles
  command: "env -i PATH=$PATH bash -c 'source {{ django_venv }}/bin/activate && source {{ django_venv }}/bin/postactivate && python {{ manage_path }}/manage.py collectstatic --noinput'"
  args:
    chdir: "{{ django_root }}"
  remote_user: "{{ django_user }}"

- name: Copy static assets to conductor 
  synchronize:
    src: "{{ django_static_root }}"
    dest: /tmp/django/ 
    mode: pull